/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package ShoppingCartApp

import spock.lang.Specification

class AppTest extends Specification {
    def "adding bad item"() {
        setup:
        def app = new App()

        when:
        app.addItem(new ShoppingItems("bread", 2.99, two))

        then:
        thrown Exception
    }
    def "item is added"() {
        setup:
        def app = new App()
        ShoppingItems bread = new ShoppingItems("bread", 2.99, 3)

        when:
        app.addItem(bread)
        int sizeList = app.itemList.size()

        then:
        sizeList == 1
    }
    def "item is deleted"() {
        setup:
        def app = new App()
        ShoppingItems bread = new ShoppingItems("bread", 2.99, 3)
        ShoppingItems eggs = new ShoppingItems("eggs", 3.49, 1)

        when:
        app.addItem(bread)
        app.addItem(eggs)
        app.deleteItem(bread)
        int sizeList = app.itemList.size()

        then:
        sizeList == 1
    }
    def "show list with no items"() {
        setup:
        def app = new App()

        when:
        app.displayItem()

        then:
        final List lines = capture

    }
    def "item is edited"() {
        setup:
        def app = new App()
        ShoppingItems bread = new ShoppingItems("bread", 2.99, 3)

        when:
        app.addItem(bread)

        then:
        bread.getPrice() == 2.99
    }
}
