/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.ShoppingCartApp;

import main.java.ShoppingCartApp.controller.ShoppingCartController;

public class App {

    public static void main(String[] args) {

        ShoppingCartController shoppingCartController = new ShoppingCartController();
        shoppingCartController.run();
    }
}
